#!filepath: docker-compose.yaml
name: ocr
services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  ocr-api-cpu:
    build:
      context: .
      dockerfile: Dockerfile.cpu
    image: ocr-api:cpu
    container_name: ocr-api-cpu
    environment:
      - OLLAMA_HOST=ollama
      - PADDLEOCR_MODEL_DIR=/app/paddleocr_models
      - EASYOCR_MODEL_DIR=/app/easyocr_models
      - LLAVA_MODEL_DIR=/app/llava_models
      - PP_OCR_V5_MODEL_DIR=/app/pp_ocrv5_models
      - PP_STRUCTURE_V3_MODEL_DIR=/app/pp_structurev3_models
      - PP_CHATOCR_V4_MODEL_DIR=/app/pp_chatocrv4_models
    ports:
      - "8000:8000"
    volumes:
      - ./easyocr_models:/app/easyocr_models
      - ./llava_models:/app/llava_models
      - ./paddleocr_models:/app/paddleocr_models
      - ./pp_ocrv5_models:/app/pp_ocrv5_models
      - ./pp_structurev3_models:/app/pp_structurev3_models
      - ./pp_chatocrv4_models:/app/pp_chatocrv4_models
    depends_on:
      - ollama
    restart: unless-stopped

  ocr-api-gpu:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    image: ocr-api:gpu
    container_name: ocr-api-gpu
    environment:
      - OCR_USE_GPU=true
      - OLLAMA_HOST=ollama
      - PADDLEOCR_USE_GPU=true
      - PADDLEOCR_MODEL_DIR=/app/paddleocr_models
      - EASYOCR_MODEL_DIR=/app/easyocr_models
      - LLAVA_MODEL_DIR=/app/llava_models
      - PP_OCR_V5_MODEL_DIR=/app/pp_ocrv5_models
      - PP_STRUCTURE_V3_MODEL_DIR=/app/pp_structurev3_models
      - PP_CHATOCR_V4_MODEL_DIR=/app/pp_chatocrv4_models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "8001:8000"
    volumes:
      - ./easyocr_models:/app/easyocr_models
      - ./llava_models:/app/llava_models
      - ./paddleocr_models:/app/paddleocr_models
      - ./pp_ocrv5_models:/app/pp_ocrv5_models
      - ./pp_structurev3_models:/app/pp_structurev3_models
      - ./pp_chatocrv4_models:/app/pp_chatocrv4_models
    depends_on:
      - ollama
    restart: unless-stopped

volumes:
  ollama_data:
