#!filepath: docker-compose.yaml
name: ocr
services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  ocr-api-cpu:
    build:
      context: .
      dockerfile: Dockerfile.production
      target: cpu
    image: ocr-api:cpu
    container_name: ocr-api-cpu
    environment:
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434
      - VISION_MODEL_NAME=llava:latest
      - PADDLEOCR_HOME=/opt/paddleocr_models
      - EASYOCR_MODEL_DIR=/opt/easyocr_models
    ports:
      - "8000:8000"
    volumes:
      - ./easyocr_models:/opt/easyocr_models:ro
      - ./paddleocr_models:/opt/paddleocr_models:ro
    depends_on:
      - ollama
    restart: unless-stopped

  ocr-api-gpu:
    build:
      context: .
      dockerfile: Dockerfile.production
      target: gpu
    image: ocr-api:gpu
    container_name: ocr-api-gpu
    environment:
      - OCR_USE_GPU=true
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434
      - VISION_MODEL_NAME=llava:latest
      - PADDLEOCR_USE_GPU=true
      - PADDLEOCR_HOME=/opt/paddleocr_models
      - EASYOCR_MODEL_DIR=/opt/easyocr_models
    gpus: all
    ports:
      - "8001:8000"
    volumes:
      - ./easyocr_models:/opt/easyocr_models:ro
      - ./paddleocr_models:/opt/paddleocr_models:ro
    depends_on:
      - ollama
    restart: unless-stopped

volumes:
  ollama_data:
